version: '3'
services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    container_name: test-rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: testuser
      RABBITMQ_DEFAULT_PASS: testpassword
    networks:
      - test-network

  redis:
    image: redis:latest
    container_name: test-redis
    ports:
      - '6379:6379'
    networks:
      - test-network

networks:
  test-network:
    driver: bridge
