services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'
  rabbitmq:
    image: 'rabbitmq:3-management'
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'

  producer:
    build: ./app/producer
    container_name: producer
    depends_on:
      - rabbitmq
      - redis
    env_file:
      - .env

  consumer:
    build: ./app/consumer
    container_name: consumer
    depends_on:
      - rabbitmq
      - redis
    env_file:
      - .env
    ports:
      - '3000:3000'
